apiVersion: v1
data:
  images.json: |-
    [
      "https://i.imgflip.com/7jmwqn.jpg",
      "https://i.imgflip.com/7jmwe9.jpg"
    ]
kind: ConfigMap
metadata:
  name: images-json
  labels:
    app: random-meme
